### ISSUE TITLE
Block.connect can't find devices with `aio:` prefix

### ISSUE THREAD

**Issue by timbertson** [mirage/mirage-block-xen#44]
My config.ml uses:

    let fs = fat_of_files ~dir:"./data" ()

and i've added the disk to my .xl config with:

    disk = [ 'format=raw,vdev=xvda,access=rw,target=fat1.img' ]

But when I try to boot that, I get:

	Block.connect fat1.img: unable to match 'fat1.img' to any available devices [ 51712 ]
	Block.connect fat1.img: could not find device
	Fatal error: exception Failure("fat2")
	Raised at file "src/core/lwt.ml", line 782, characters 22-23
	Called from file "lib/main.ml", line 58, characters 10-20
	Called from file "main.ml", line 124, characters 2-54
	Mirage exiting with status 2

Doing some digging:

    $ xenstore-read `xl block-list console | awk '/backend/ { print $7"/params" }'`
    aio:fat1.img

The only way I could get mirage to use the right device was to edit config.ml to instead use:

    let fs = fat (block_of_file "aio:fat1.img")

... which seems rather hacky. This is the first time I've used xen though, so there could be plenty I'm doing wrong ;)

I'm running xen xen-4.5.0 locally (in VirtualBox, with NixOS as dom0). I haven't been able to get `xe` working remotely yet, so I'm currently just copying files across and using `xl` directly on dom0.

**Comment by djs55** [comment]
According to [xl-disk-configuration](http://xenbits.xen.org/docs/4.6-testing/misc/xl-disk-configuration.txt), xl supports a number of deprecated prefixes:
```
tapdisk:  tap2:  aio:  ioemu:  file:  phy:
```
which sometimes can be stacked:

> in yet other cases it would be necessary
> to specify several of these, for example:
>   "tap:aio:/some/path..."
> 
> All of these prefixes are now stripped and ignored.

So I think the answer is to do what libxl does: strip and ignore these prefixes. Hopefully the problem is disappearing as people upgrade to more recent Xen versions.

**Comment by djs55** [comment]
Sorry it took me a while to investigate this. Let me know if you still see it on mirage-block-volume 1.4.0 or later.

**Comment by djs55** [comment]
FYI mirage-block-xen.1.4.0 released in [ocaml/opam-repository#5978]
